


spring:
  application:
    name: quan-li-sach
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/quan-li-sach-database
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

default:
  password: 123456
google:
  verifyUrl: https://www.googleapis.com/oauth2/v3/userinfo?access_token=
jwt:
  secret: K1LqzK6eeD0g0BfgOg7SKs2K1LqzK6eeD0g0BfgOg7SK1LqzK6eeD0g0BfgOg7S
logging:
  file:
    name: logs/quan-li-sach.log
  level:
    org:
      springframework:
        cache: error
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 100MB
      max-history: 7
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
paging:
  default:
    page: 0
    size: 20
server:
  error:
    include-message: always
#  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
